# Encoding of dataset

In [13]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [19]:
data=pd.read_csv("https://raw.githubusercontent.com/jbrownlee/Datasets/master/breast-cancer.csv")
data.head()

'40-49'  'premeno'  '15-19'  '0-2'  'yes'  '3'  'right'   'left_up'   'no'  \
0  '50-59'     'ge40'  '15-19'  '0-2'   'no'  '1'  'right'   'central'   'no'   
1  '50-59'     'ge40'  '35-39'  '0-2'   'no'  '2'   'left'  'left_low'   'no'   
2  '40-49'  'premeno'  '35-39'  '0-2'  'yes'  '3'  'right'  'left_low'  'yes'   
3  '40-49'  'premeno'  '30-34'  '3-5'  'yes'  '2'   'left'  'right_up'   'no'   
4  '50-59'  'premeno'  '25-29'  '3-5'   'no'  '2'  'right'   'left_up'  'yes'   

      'recurrence-events'  
0  'no-recurrence-events'  
1     'recurrence-events'  
2  'no-recurrence-events'  
3     'recurrence-events'  
4  'no-recurrence-events'

In [20]:
data.shape

(285, 10)

In [23]:
data=data.values

In [32]:
#separating into input and output columns
X=data[:,:-1].astype(str)
y=data[:,-1].astype(str)
print(X.shape)
print(y.shape)

(285, 9)
(285,)


# Ordinal Encoding

In [69]:
ordinal_encoder=OrdinalEncoder()
X=ordinal_encoder.fit_transform(X)
label_encoder=LabelEncoder()
y=label_encoder.fit_transform(y)

In [70]:
print(X[:5,:])
print(y[:5])

[[3. 0. 2. 0. 0. 0. 1. 0. 0.]
 [3. 0. 6. 0. 0. 1. 0. 1. 0.]
 [2. 2. 6. 0. 1. 2. 1. 1. 1.]
 [2. 2. 5. 4. 1. 1. 0. 4. 0.]
 [3. 2. 4. 4. 0. 1. 1. 2. 1.]]
[0 1 0 1 0]


In [62]:
#splitting data into training and test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=1)

We can now fit the OrdinalEncoder on the training dataset and use it to transform the train and test dataset

In [63]:
#ordinal encode input variable
ordinal_encoder=OrdinalEncoder()
ordinal_encoder.fit(X_train)
X_train_oe=ordinal_encoder.transform(X_train)
X_test_oe=ordinal_encoder.fit_transform(X_test)

In [64]:
#ordinal encode target variable
label_encoder=LabelEncoder()
label_encoder.fit(y_train)
y_train_oe=label_encoder.transform(y_train)
y_test_oe=label_encoder.transform(y_test)

We will now fit the LogisticRegression algorithm on the training dataset and evaluate the test dataset

In [65]:
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train_oe,y_train_oe)
y_pred_oe=model.predict(X_test_oe)
accu_oe=accuracy_score(y_test_oe,y_pred_oe)
print(accu_oe*100)

72.63157894736842


# OneHot Encoding

In [82]:
# one-hot encode input variables
one_hot_encoder=OneHotEncoder()
one_hot_encoder.fit(X_train)
X_train_ohe=one_hot_encoder.transform(X_train)
X_test_ohe=one_hot_encoder.fit_transform(X_test)

In [83]:
# ordinal encode target variable
label_encoder=LabelEncoder()
label_encoder.fit(y_train)
y_train_ohe=label_encoder.transform(y_train)
y_test_ohe=label_encoder.transform(y_test)

We will now fit the LogisticRegression algorithm on the training dataset and evaluate the test dataset

In [86]:
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train_ohe,y_train_ohe)
y_pred_ohe=model.predict(X_test_ohe)
accu_ohe=accuracy_score(y_test_ohe,y_pred_ohe)
print(accu_ohe*100)

C:\Users\Sakshi Gupta\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


ValueError: X has 164 features per sample; expecting 170